# Generated by Django 4.0.6 on 2022-08-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerplane',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='People capacity'),
        ),
        migrations.AlterField(
            model_name='series',
            name='code',
            field=models.PositiveIntegerField(unique=True, verbose_name='Series unique id'),
        ),
    ]
