# Generated by Django 4.0.6 on 2022-08-02 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_alter_passengerplane_capacity_alter_series_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerplane',
            name='capacity',
            field=models.PositiveSmallIntegerField(verbose_name='People capacity'),
        ),
        migrations.AlterField(
            model_name='series',
            name='code',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Series unique id'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.CheckConstraint(check=models.Q(('code__gte', 1)), name='planes_series_code_gte_1'),
        ),
    ]
